#pragma once

#include "chassis/AbstractChassis.hpp"                        // IWYU pragma: keep
#include "chassis/ChassisCommand.hpp"                         // IWYU pragma: keep
#include "chassis/DiffChassis.hpp"                            // IWYU pragma: keep
#include "chassis/HDriveChassis.hpp"                          // IWYU pragma: keep
#include "chassis/XDriveChassis.hpp"                          // IWYU pragma: keep
#include "controller/AbstractController.hpp"                  // IWYU pragma: keep
#include "controller/ArcPIDController.hpp"                    // IWYU pragma: keep
#include "controller/ArcPIDControllerBuilder.hpp"             // IWYU pragma: keep
#include "controller/BoomerangController.hpp"                 // IWYU pragma: keep
#include "controller/BoomerangControllerBuilder.hpp"          // IWYU pragma: keep
#include "controller/PIDController.hpp"                       // IWYU pragma: keep
#include "controller/PIDControllerBuilder.hpp"                // IWYU pragma: keep
#include "controller/SwingController.hpp"                     // IWYU pragma: keep
#include "controller/SwingControllerBuilder.hpp"              // IWYU pragma: keep
#include "exit_conditions/AbstractExitCondition.hpp"          // IWYU pragma: keep
#include "exit_conditions/ExitConditions.hpp"                 // IWYU pragma: keep
#include "exit_conditions/SettleExitCondition.hpp"            // IWYU pragma: keep
#include "exit_conditions/TimeOutExitCondition.hpp"           // IWYU pragma: keep
#include "exit_conditions/ToleranceAngularExitCondition.hpp"  // IWYU pragma: keep
#include "exit_conditions/ToleranceLinearExitCondition.hpp"   // IWYU pragma: keep
#include "localizer/ADILocalizer.hpp"                         // IWYU pragma: keep
#include "localizer/ADILocalizerBuilder.hpp"                  // IWYU pragma: keep
#include "localizer/AbstractLocalizer.hpp"                    // IWYU pragma: keep
#include "localizer/GPSLocalizer.hpp"                         // IWYU pragma: keep
#include "localizer/IMELocalizer.hpp"                         // IWYU pragma: keep
#include "localizer/IMELocalizerBuilder.hpp"                  // IWYU pragma: keep
#include "localizer/TrackingWheelLocalizer.hpp"               // IWYU pragma: keep
#include "localizer/TrackingWheelLocalizerBuilder.hpp"        // IWYU pragma: keep
#include "selector/Selector.hpp"                              // IWYU pragma: keep
#include "utils/Point.hpp"                                    // IWYU pragma: keep
#include "utils/Pose.hpp"                                     // IWYU pragma: keep
#include "utils/angle.hpp"                                    // IWYU pragma: keep
#include "utils/debug.hpp"                                    // IWYU pragma: keep
#include "utils/flags.hpp"                                    // IWYU pragma: keep